name: Deploy

on:
  push:
    branches: [main]
jobs:
  flatpak:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-43
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        dnf -y install docker
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      name: "Build"
      with:
        bundle: fermion.flatpak
        manifest-path: co.tauos.Fermion.json
        cache-key: flatpak-builder-${{ github.sha }}
        repository-name: catalogue
        repository-url: https://repo.tauos.co/catalogue.flatpakrepo
        arch: ${{ matrix.arch }}
    - uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v3
      name: "Deploy"
      with:
        repository: stable
        flat-manager-url: https://catalogue.tauos.co
        token: ${{ secrets.FLATPAK_REPO_TOKEN }}
